version: '3.8'

services:
  db:
    container_name: postgres1
    image: postgres
    environment:
      POSTGRES_USER: "${USERNAME_DB}"
      POSTGRES_PASSWORD: "${PASSWORD_DB}"
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  app:
    image: arjanaternava/amigoscodecourse-fullstack
    container_name: amigoscodecourse-fullstack
    environment:
      SPRING_DATASOURCE_URL: "${DATABASE_CONTAINER_URL}"
      SPRING_DATASOURCE_USERNAME: "${USERNAME_DB}"
      SPRING_DATASOURCE_PASSWORD: "${PASSWORD_DB}"
    ports:
      - "8080:3000"
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db: