server:
  port: 3000
  error:
    include-message: always

spring:
  main:
      web-application-type: servlet
  datasource:
    url: ${DATABASE_URL}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
